spring.application.name=notification-service
server.port=9876
# Mail Properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=7c1cb5a7dd6075
spring.mail.password=7e1dfbb1498d56
spring.mail.protocol=smtp

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificationService

# Error-handling deserializers
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Schema Registry
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8085
spring.kafka.consumer.properties.specific.avro.reader=true


# Observability and Tracing
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=notification-service
management.tracing.sampling.probability=1.0

# Loki URL
loki.url=http://localhost:3100/loki/api/v1/push

